language: python
python:
  - 2.7

sudo: false

addons:
  apt:
    packages:
    - gcc
    - gfortran
    - libopenmpi-dev
    - libmumps-seq-dev
    - libblas-dev
    - liblapack-dev

# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython ipython nose
  - pip install nose-cov python-coveralls
  - python setup.py install
  - python setup.py build_ext --inplace

# Run test
script:
  - nosetests --with-cov --cov pymatsolver --cov-config .coveragerc -v -s

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

notifications:
  email:
    - rowanc1@gmail.com
